# Default Sample Profile for FREENAS Backup Host
# !! Do not edit this file! !!

# Freenas Options
# RSYNC_HOST='freenas'
# RSYNC_BASE='/mnt/vol1/backup'
RSYNC_HOST='freenas'
RSYNC_BASE='/mnt/vol1/backup'
RSYNC_USER='your-user'
RSYNC_PASSWORD=''
RSYNC_OPTS="--archive --verbose"
RSYNC_MAC='aa:bb:cc:dd:ee:ff'
